"""init

Revision ID: 59628dea39ff
Revises:
Create Date: 2024-01-11 18:16:54.001595

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "59628dea39ff"
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # No tables to create - user table removed as it's not used
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # No tables to drop - user table was removed
    pass
    # ### end Alembic commands ###
